name: CI/CD

on:
  push:
    branches:
      - develop
    tags:
      - "*"
  workflow_dispatch:
    tags:
      - "*"

jobs:
  build:
    uses: keinou/github-actions/.github/workflows/build-and-push-node-app.yaml@main
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

  deploy:
    uses: keinou/github-actions/.github/workflows/redeploy-railway.yaml@main
    needs: build
    secrets:
      SERVICE: burst-ms-gatekeeper
      TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  notification:
    if: always()
    name: Notification
    uses: keinou/github-actions/.github/workflows/notification.yaml@main
    needs: ["build", "deploy"]
    secrets:
      webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
